### PR TITLE
Change rfio nshost default

### PR DESCRIPTION
**Pull request by gwarf**
Update default value for nshost, as current code was resulting in an empty string. Also unquote alone variables.

### CODE REVIEW

**Comment by andrea-manzi** [comment]
thanks again:-)

**Comment by gwarf** [comment]
Thanks for the merges!

**Comment by andrea-manzi** [comment]
mmm, i doing some tests and i think i have to revert this change ( or adapt it ), cause we assume in our templates that dpmhost and nshost are the same ( which is basically true) so in the manifest we suggest to fill only the dpmhost:

https://github.com/cern-it-sdc-id/lcgdm-puppet-examples/blob/master/dpm/disk/disknode.pp#L117

and the nshost will take the same value..with yuor change the nshost using that manifest we will wrong..

so either i push this change but then i have to tell everyone to adapt the manifest, or i have to revert or i have to find a solution which will not break existing assumptions

**Comment by gwarf** [comment]
The problem was that without setting nshost, it was resulting in an empty string, and thus in the rfio configuration file the DPNS_HOST setting wasn't set correctly. Before this commit I had to explicitely add the nshost parameter to get it populated. Still only tested on puppet 4, but IIRC I already saw similar things with puppet 3.x code, to me it looks like that using a parameter value to set a value for one other parameter in the parameter list is not working as expected.

**Comment by gwarf** [comment]
I was able to find a message from Henrik Lindberg from puppetlabs confirming that it can/cannot work depending on versions: https://groups.google.com/d/msg/puppet-users/BjtnEtoD8NA/vm0btva1yYwJ

**Comment by andrea-manzi** [comment]
i have made some changes on develop branch and tested it, it looks ok now ( no parameter value and kept the old behaviour)

https://github.com/cern-it-sdc-id/puppet-lcgdm/blob/a653e22b378c0f33de34787c33b6a990230f46ea/manifests/rfio.pp

what do you think?

**Comment by gwarf** [comment]
Even if it might not be as clean/simple I think that at least this way it will also work and allows to keep examples/existing code untouched.

**Pull request merged**
