### PR TITLE
shift augeas: deploy augeas shift lens using pluginsync 

### PR DESCRIPTION
**Pull request by gwarf**
Deploy augeas shift lens with pluginsync in order to be compatible with new puppet versions/packaging, as with puppet 4 all-in-one-package augeas is packaged too and lenses are located in /opt/puppetlabs/puppet/share/augeas/lenses instead of /usr/share/augeas/lenses.
See https://docs.puppetlabs.com/guides/plugins_in_modules.html#module-structure and https://docs.puppetlabs.com/puppet/latest/reference/types/augeas.html#augeas-attribute-load_path for official documentation.

### CODE REVIEW

**Comment by andrea-manzi** [comment]
Hello,
is this change compatible with puppet 3.x?
thanks!
Andrea

**Comment by gwarf** [comment]
HI Andrea,
Yes it is compatible with both puppet 4 and 3.8 (I don't know exactlly when it was added, but I presume it is quite old), please see the Puppet 3.8 documentation: https://docs.puppetlabs.com/puppet/3.8/reference/types/augeas.html#augeas-attribute-load_path 
Thanks!
Baptiste

**Comment by andrea-manzi** [comment]
Ok i will make some tests, cause could be that people is still using old versions ( like 2.7 from EPEL6) and see if this change is fine
thanks!
Andrea

**Comment by gwarf** [comment]
OK, thanks. Sometimes adminstrating grids feels like doing some time travel ;)
Let's hope that it will work, it would be cleaner than using tests in the manifests to find the puppet version/augeas facts location.

**Comment by andrea-manzi** [comment]
we have documented to use puppet 3.x at minimum , so this change can be merged

**Comment by andrea-manzi** [comment]
Hello,
just to say that i need to readd part of the code cause this PR broke the augeas for shift.conf when running puppet in standalone mode 

i made this changes

https://github.com/cern-it-sdc-id/puppet-lcgdm/commit/b3a336e7988d7c712eddce237766d9fe16d80af0

which should work both for puppet3 and 4 and both using a puppet master or not

**Pull request merged**
